esphome:
  name: wii-balance-board
  friendly_name: "Wii Balance Board"

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino
    sdkconfig_options:
      CONFIG_BT_ENABLED: y
      CONFIG_BLUEDROID_ENABLED: y
      CONFIG_CLASSIC_BT_ENABLED: y
      CONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY: y

# Enable logging
logger:
  level: INFO

# Local device dashboard
web_server:
  port: 80

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT

external_components:
  - source:
      type: local
      path: ./wii_balance_board_component
    components: [ wii_balance_board ]

wii_balance_board:
  id: wbb
  standard_deviation: 0.3
  led_pin: 2
  temperature_sensor:
    name: "Balance Board Temperature"
  reference_temperature_sensor:
    name: "Balance Board Reference Temperature"
  battery_level:
    name: "Balance Board Battery Level"
  weight:
    name: "Balance Board Weight"
  syncing:
    name: "Balance Board Syncing"

button:
  - platform: template
    name: "Start Sync"
    on_press:
      then:
        - lambda: 'id(wbb)->sync(true);'
